title: Hiruni Kegalle
logo: /assets/img/Hiruni-round.png
description: PhD Candidate, RMIT University, Australia.
show_downloads: false
theme: jekyll-theme-minimal
github:
  is_project_page: false
layout: publications
permalink: /publications
markdown: kramdown
kmarkdown:
  input: GFM
